apiVersion: v1
kind: ReplicationController
metadata:
  name: mypod1
spec:
    replicas: 3
    template:
      metadata:
        labels:
          app: test
      spec:
        containers:
         - image: nginx
           name: mycont
           ports:
             - containerPort: 80
           livenessProbe:
               httpGet:
                   path: /index.html
                   port: 80
               initialDelaySeconds: 10
               periodSeconds: 20
               failureThreshold: 4
