apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myrspod
spec:
  replicas: 3
  selector:
   matchLabels:
    env: dev
  template:
    metadata:
      labels:
         env: dev
    spec:
      containers:
          - name: nginxcont
            image: nginx
            ports:
              - containerPort: 80
