apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mydspod
spec:
  selector:
   matchLabels:
    env: dev
  template:
    metadata:
      labels:
         env: dev
    spec:
      containers:
          - name: nginxcont
            image: nginx
            ports:
              - containerPort: 80